### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by tanujjain** [prateekralhan/Imagededup---Streamlit#1]
Following suggestions:

1. Cleaner `requirements.txt`: You seem to have the output of `pip freeze` as requirements.txt, which is not great since pip resolver works differently for different platforms/versions. Instead, use specific versions of dependencies you actually import in your app, especially third party ones (like pandas, imagededup, etc.)
2. Python version you use is python 3.7, which is no longer supported by imagededup (from 0.3.0 onwards). So, please switch it to python 3.8/9/10.
3. There are Heroku specific files in there, whereas the Readme instructions seem to be focussed upon running it locally. You could either remove the Heroku specific part (while keeping the docker part anyway), or include instructions to deploy to Heroku as well.

**Comment by prateekralhan** [comment]
@tanujjain , Thank you for these suggestions.

I have made all the changes.
